---
title: "Matrix Heatmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Libraries
```{r}
install.packages("readxl")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("pheatmap")
```

## Load Data
```{r}
# Load necessary libraries
library(readxl)
library(ggplot2)
library(reshape2)

# Load the matrix from Excel
file_path <- "output/Ruby_output/similarity_checker(CREATIVE with only AI).xlsx"
matrix_data <- read_excel(file_path, sheet = 1) # Read the first sheet

# Print the first few rows
head(matrix_data)
```
## Heatmap Viz
```{r}
# Load necessary libraries
library(pheatmap)

# Remove user_id column for the heatmap
matrix_data_clean <- as.matrix(matrix_data[,-1])

# Set row and column names to user_id
rownames(matrix_data_clean) <- matrix_data$user_id
colnames(matrix_data_clean) <- matrix_data$user_id

# Plot heatmap
pheatmap(matrix_data_clean, cluster_rows=TRUE, cluster_cols=TRUE)
```

```{r}
# Sorted Heat Map

# Step 1: 計算每一列的總和
column_sums <- colSums(matrix_data, na.rm = TRUE)

# Step 2: 根據列總和對列排序
sorted_matrix <- matrix_data[, order(column_sums, decreasing = TRUE)]

# Step 3: 繪製熱圖，使用排序後的數據
library(pheatmap)
pheatmap(sorted_matrix, cluster_rows = TRUE, cluster_cols = FALSE)

# pheatmap(matrix_data_clean,
#          cluster_rows=TRUE,
#          cluster_cols=TRUE,
#          distance_rows = "manhattan",   # 自定義行之間的距離度量方法
#          distance_cols = "euclidean",   # 自定義列之間的距離度量方法
#          clustering_method = "average"  # 自定義聚類方法
# )
```